"""Create email_subs table

Revision ID: 33b2ead3303a
Revises: 2767bf3fc4cd
Create Date: 2025-04-04 21:34:07.984417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b2ead3303a'
down_revision: Union[str, None] = '2767bf3fc4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_subs',
    sa.Column('email', sa.String(length=110), nullable=False),
    sa.Column('date_sub', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_subs')
    # ### end Alembic commands ###