"""Add hobbies table

Revision ID: 7888a46c78b4
Revises: a47d6def31ac
Create Date: 2025-07-30 00:07:25.558077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7888a46c78b4'
down_revision: Union[str, None] = 'a47d6def31ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobby_brands',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hobby_game_series',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hobbies',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), server_default='', nullable=False),
    sa.Column('article', sa.String(length=10), nullable=False),
    sa.Column('size', sa.String(length=18), server_default='', nullable=False),
    sa.Column('language', sa.Enum('UKRAINIAN', 'ENGLISH', name='hobbylanguages'), server_default='UKRAINIAN', nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('details_count', sa.Integer(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('seria_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['hobby_brands.id'], ),
    sa.ForeignKeyConstraint(['seria_id'], ['hobby_game_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    sa.UniqueConstraint('code')
    )
    op.create_table('hobby_ages_association',
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.Column('board_game_age', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_game_age'], ['board_game_ages.id'], ),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ),
    sa.PrimaryKeyConstraint('hobby_id', 'board_game_age', 'id')
    )
    op.create_table('hobby_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), server_default='', nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hobby_images')
    op.drop_table('hobby_ages_association')
    op.drop_table('hobbies')
    op.drop_table('hobby_game_series')
    op.drop_table('hobby_brands')
    # ### end Alembic commands ###