"""Add book_info table and relate it with books

Revision ID: c2de53c6ab27
Revises: db0f2b577730
Create Date: 2025-04-10 11:41:34.085419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2de53c6ab27'
down_revision: Union[str, None] = 'db0f2b577730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_info',
    sa.Column('in_stock', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), server_default='0', nullable=False),
    sa.Column('illustrations', sa.String(length=255), server_default='', nullable=False),
    sa.Column('ISBN', sa.String(length=255), server_default='', nullable=False),
    sa.Column('cover_type', sa.Enum('SOLID', 'SOFT', name='covertypes'), server_default='SOLID', nullable=False),
    sa.Column('pages_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_has_cashback', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_has_esupport', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('format', sa.Enum('PAPER', 'ELECTRONIC', 'AUDIO', name='bookformats'), server_default='PAPER', nullable=False),
    sa.Column('language', sa.Enum('UKRAINIAN', 'ENGLISH', name='booklanguages'), server_default='UKRAINIAN', nullable=False),
    sa.Column('publishing_year', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_published_at', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('characteristics', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_info_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_book_info', 'book_info', ['book_info_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_info', type_='foreignkey')
        batch_op.drop_column('book_info_id')

    op.drop_table('book_info')
    # ### end Alembic commands ###