"""Connected notebook_categories to books table

Revision ID: b8eb2338729f
Revises: 4d506006e870
Create Date: 2025-09-01 00:11:07.081228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8eb2338729f'
down_revision: Union[str, None] = '4d506006e870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook_categories',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('images_src', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notebook_category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notebook_category_id', 'notebook_categories', ['notebook_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notebook_category_id', type_='foreignkey')
        batch_op.drop_column('notebook_category_id')

    op.drop_table('notebook_categories')
    # ### end Alembic commands ###