"""created delivery_terms table abd connected it with countries and cities via one2one relationship

Revision ID: 41407453be1b
Revises: 849f906a9d36
Create Date: 2025-06-19 01:17:30.485263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41407453be1b'
down_revision: Union[str, None] = '849f906a9d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_terms',
    sa.Column('yakaboo_shop_price', sa.Integer(), nullable=True),
    sa.Column('new_post_office_price', sa.Integer(), nullable=True),
    sa.Column('new_post_department_price', sa.Integer(), nullable=True),
    sa.Column('new_post_courier_price', sa.Integer(), nullable=True),
    sa.Column('meest_post_price', sa.Integer(), nullable=True),
    sa.Column('ukrpost_department_price', sa.Integer(), nullable=True),
    sa.Column('ukrpost_courier_price', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_terms')
    # ### end Alembic commands ###