"""added new fields in hobbies table

Revision ID: 1f257d901ff0
Revises: ffcca87aed4c
Create Date: 2025-08-14 09:23:05.203693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f257d901ff0'
down_revision: Union[str, None] = 'ffcca87aed4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

types_enum = sa.Enum("Олівець", "Ручка", "Маркер", name="types_enum")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    types_enum.create(op.get_bind())

    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packing', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type', types_enum, nullable=True))
        batch_op.drop_column('in_stock')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_column('type')
        batch_op.drop_column('color')
        batch_op.drop_column('packing')

    types_enum.drop(op.get_bind())
    # ### end Alembic commands ###