"""Add stars field in book_accessories table

Revision ID: e641c7361342
Revises: 833936cdd00d
Create Date: 2025-08-28 01:45:43.553752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e641c7361342'
down_revision: Union[str, None] = '833936cdd00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=True))
        batch_op.drop_column('theme')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', postgresql.ENUM('Класична', 'Відомі люди і песронажі', 'Література', name='accessory_theme_enum'), autoincrement=False, nullable=True))
        batch_op.drop_column('stars')

    # ### end Alembic commands ###