"""fixed board_games and board_games_age relation

Revision ID: 4e3d308f665d
Revises: 3924a0986d64
Create Date: 2025-05-21 08:15:10.024883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3d308f665d'
down_revision: Union[str, None] = '3924a0986d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###