"""updated indexes in new_post_postomats table

Revision ID: a67d4ee6be69
Revises: 665c69fa6734
Create Date: 2025-11-28 02:55:53.826117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67d4ee6be69'
down_revision: Union[str, None] = '665c69fa6734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('new_post_postomats', schema=None) as batch_op:
        batch_op.drop_index('idx_new_post_postomat_city_active', postgresql_where='(active = true)')
        batch_op.create_index('idx_new_postomat_city_active', ['city_id', 'id'], unique=False, postgresql_where=sa.text('active = true'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_post_postomats', schema=None) as batch_op:
        batch_op.drop_index('idx_new_postomat_city_active', postgresql_where=sa.text('active = true'))
        batch_op.create_index('idx_new_post_postomat_city_active', ['city_id', 'id'], unique=False, postgresql_where='(active = true)')
    # ### end Alembic commands ###