"""Create book_images table and related with books table

Revision ID: fc499d2d6860
Revises: 0722e004fbba
Create Date: 2025-07-15 13:12:34.020270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc499d2d6860'
down_revision: Union[str, None] = '0722e004fbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), server_default='', nullable=False),
    sa.Column('type', sa.Enum('COVER', 'PAGE', name='book_image_type_enum'), server_default='COVER', nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_games', schema=None) as batch_op:
        batch_op.drop_column('theme')
        batch_op.drop_column('language')

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonuses', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('bonuses')

    with op.batch_alter_table('board_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', postgresql.ENUM('UKRAINIAN', 'RUSSIAN', 'ENGLISH', 'FRENCH', 'GERMAN', 'CZECH', 'SLOVAKIAN', 'SPANISH', 'ROMANIAN', 'POLISH', 'HUNGARIAN', name='language'), server_default=sa.text("'UKRAINIAN'::language"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('theme', postgresql.ENUM('NATURE', 'VEHICLES', 'ARCHITECTURE', 'COUNTRIES_AND_CITIES', 'ART', 'MOVIES_AND_CARTOONS', 'SHIPS', 'EDUCATIONAL', 'PEOPLE', 'FANTASY', name='theme'), autoincrement=False, nullable=True))

    op.drop_table('book_images')
    # ### end Alembic commands ###