"""Deleted unique from number field in new_post_offices

Revision ID: a1c88bc8cf14
Revises: 7f55a9a67e34
Create Date: 2025-12-02 11:11:25.754592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c88bc8cf14'
down_revision: Union[str, None] = '7f55a9a67e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_post_offices', schema=None) as batch_op:
        batch_op.drop_constraint('new_post_offices_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_post_offices', schema=None) as batch_op:
        batch_op.create_unique_constraint('new_post_offices_number_key', ['number'])


    # ### end Alembic commands ###