"""create board_game_subcategories table and related with board_games table with m2m 

Revision ID: 30df72b8b7d4
Revises: dc2c0e0e5d20
Create Date: 2025-05-26 19:20:39.643758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30df72b8b7d4'
down_revision: Union[str, None] = 'dc2c0e0e5d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_game_subcategories',
    sa.Column('title', sa.Enum('Настільні ігри', 'Пазли', 'Головоломки', name='subcategories_enum'), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('board_game_subcategory_association',
    sa.Column('board_game_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_game_id'], ['board_games.code'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['board_game_subcategories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_games', schema=None) as batch_op:
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', postgresql.ENUM('BOARD', 'PUZZLE', 'CONUNDRUM', name='subcategory'), server_default=sa.text("'BOARD'::subcategory"), autoincrement=False, nullable=False))

    op.drop_table('board_game_subcategory_association')
    op.drop_table('board_game_subcategories')
    # ### end Alembic commands ###