"""Add publishings table

Revision ID: 0d96aa6ec694
Revises: 5351b8725a51
Create Date: 2025-04-14 11:38:04.888494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d96aa6ec694'
down_revision: Union[str, None] = '5351b8725a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishings',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('logo', sa.String(length=255), server_default='', nullable=False),
    sa.Column('short_description', sa.Text(), server_default='', nullable=False),
    sa.Column('long_description', sa.Text(), server_default='', nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publishing_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_book_publishing', 'publishings', ['publishing_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_publishing', type_='foreignkey')
        batch_op.drop_column('publishing_id')

    op.drop_table('publishings')
    # ### end Alembic commands ###