"""Added subcategory_banners table and related it with sub_categories table

Revision ID: 15cf997bca65
Revises: 431781e4b4d3
Create Date: 2025-10-21 17:08:03.660403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15cf997bca65'
down_revision: Union[str, None] = '431781e4b4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory_banners',
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['sub_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('subcategory_banners')
    # ### end Alembic commands ###