"""changed office_number in meest_post_offices

Revision ID: 0177a840894c
Revises: 4508c49e156a
Create Date: 2025-11-26 00:29:15.378230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0177a840894c'
down_revision: Union[str, None] = '4508c49e156a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meest_post_offices', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['office_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meest_post_offices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###