"""Added papers, size, pages_color, type fields into book_info table

Revision ID: 0b01538fc02b
Revises: 7f081d9bc21a
Create Date: 2025-09-05 01:30:56.069269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b01538fc02b'
down_revision: Union[str, None] = '7f081d9bc21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    pagestype = sa.Enum('LINES', 'CELL', 'OBLIQUE', 'SIMPLE', name='pagestype')
    pagestype.create(op.get_bind(), checkfirst=True)

    sizetypes = sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='sizetypes')
    sizetypes.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('papers', sa.Enum('LINES', 'CELL', 'OBLIQUE', 'SIMPLE', name='pagestype'), nullable=True))
        batch_op.add_column(sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='sizetypes'), nullable=True))
        batch_op.add_column(sa.Column('pages_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('pages_color')
        batch_op.drop_column('size')
        batch_op.drop_column('papers')

    sa.Enum(name='pagestype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sizetypes').drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###