"""Added a container_title field in knowledges table

Revision ID: 6a782ce09488
Revises: ff8a37bacb81
Create Date: 2025-09-22 06:40:06.544977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a782ce09488'
down_revision: Union[str, None] = 'ff8a37bacb81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('knowledges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_title', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledges', schema=None) as batch_op:
        batch_op.drop_column('container_title')

    # ### end Alembic commands ###