"""Added gift, gift_brands, gift_categories, gift_images, gift_info, gift_series, gift_subcategories, gift_ages_association tables

Revision ID: 8a3ecaf5d389
Revises: 310b6286ed64
Create Date: 2025-09-10 06:57:15.687851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3ecaf5d389'
down_revision: Union[str, None] = '310b6286ed64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_brands',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('gift_categories',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('images_src', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('gift_info',
    sa.Column('in_stock', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('ISBN', sa.String(length=50), nullable=False),
    sa.Column('bonuses', sa.Integer(), nullable=True),
    sa.Column('is_has_esupport', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_has_cashback', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('pages_count', sa.Integer(), nullable=True),
    sa.Column('item_size', sa.String(length=20), nullable=True),
    sa.Column('packing_size', sa.String(length=20), nullable=True),
    sa.Column('illustrations', sa.String(length=30), nullable=True),
    sa.Column('packing_type', sa.String(length=40), nullable=True),
    sa.Column('cover_type', sa.String(length=40), nullable=True),
    sa.Column('colors', sa.String(length=150), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('publishing_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Enum('UKRAINIAN', 'ENGLISH', 'SPANISH', 'POLISH', 'FRANCE', 'GERMAN', name='gift_languages'), server_default='UKRAINIAN', nullable=False),
    sa.Column('gift_type', sa.Enum('BAG', 'CERTIFICATE', 'MARKS', name='gift_type'), nullable=True),
    sa.Column('theme', sa.Enum('FAMOUS_PEOPLE', 'OTHER', 'ANIMALS', 'LITERATURE', name='gift_theme'), nullable=True),
    sa.Column('event', sa.Enum('OTHER', 'ALL_CASES', name='gift_event'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ISBN'),
    sa.UniqueConstraint('code')
    )
    op.create_table('gift_series',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('gift_subcategories',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=55), nullable=False),
    sa.Column('images_src', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['gift_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_top', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_in_chart', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('gift_info_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('seria_id', sa.Integer(), nullable=False),
    sa.Column('gift_category_id', sa.Integer(), nullable=True),
    sa.Column('gift_subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['gift_brands.id'], ),
    sa.ForeignKeyConstraint(['gift_category_id'], ['gift_categories.id'], name='fk_gift_categories'),
    sa.ForeignKeyConstraint(['gift_info_id'], ['gift_info.id'], name='fk_gift_info'),
    sa.ForeignKeyConstraint(['gift_subcategory_id'], ['gift_subcategories.id'], name='fk_gift_subcategories'),
    sa.ForeignKeyConstraint(['seria_id'], ['gift_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('gift_ages_association',
    sa.Column('gift_id', sa.Integer(), nullable=False),
    sa.Column('board_game_age_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_game_age_id'], ['board_game_ages.id'], ),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ),
    sa.PrimaryKeyConstraint('gift_id', 'board_game_age_id', 'id')
    )
    op.create_table('gift_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), server_default='', nullable=False),
    sa.Column('gift_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    op.drop_table('gift_images')
    op.drop_table('gift_ages_association')
    op.drop_table('gifts')
    op.drop_table('gift_subcategories')
    op.drop_table('gift_series')
    op.drop_table('gift_info')
    op.drop_table('gift_categories')
    op.drop_table('gift_brands')
    # ### end Alembic commands ###