"""added indexes in new_post_postomats table

Revision ID: 665c69fa6734
Revises: 0bb040a77ad1
Create Date: 2025-11-28 02:33:06.671939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665c69fa6734'
down_revision: Union[str, None] = '0bb040a77ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('new_post_postomats', schema=None) as batch_op:
        batch_op.create_index('idx_new_post_postomat_active', [sa.literal_column('id')], unique=False, postgresql_where=sa.text('active = true'))
        batch_op.create_index('idx_new_post_postomat_city_active', [sa.literal_column('city_id'), sa.literal_column('id')], unique=False, postgresql_where=sa.text('active = true'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_post_postomats', schema=None) as batch_op:
        batch_op.drop_index('idx_new_post_postomat_city_active', postgresql_where=sa.text('active = true'))
        batch_op.drop_index('idx_new_post_postomat_active', postgresql_where=sa.text('active = true'))

    # ### end Alembic commands ###