"""Added expires_at column in promo_codes table

Revision ID: 70c5492fcbb6
Revises: 2dd53597e4c6
Create Date: 2025-11-19 08:33:05.392556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c5492fcbb6'
down_revision: Union[str, None] = '2dd53597e4c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_column('expires_at')


    # ### end Alembic commands ###