"""Added nullable to seria_id and seria fields in gifts

Revision ID: ff8a37bacb81
Revises: 7b0e73120bc9
Create Date: 2025-09-15 10:03:21.686768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8a37bacb81'
down_revision: Union[str, None] = '7b0e73120bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.alter_column('seria_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('gifts', schema=None) as batch_op:
        batch_op.alter_column('seria_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###