"""Add images_src field in accessories_category table

Revision ID: 2f6abb2f358f
Revises: 82b19c46e2bd
Create Date: 2025-08-25 12:47:30.386937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6abb2f358f'
down_revision: Union[str, None] = '82b19c46e2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accessories_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_src', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('accessories_categories', schema=None) as batch_op:
        batch_op.drop_column('images_src')

    # ### end Alembic commands ###