"""add subcategory field to board_games table

Revision ID: dc2c0e0e5d20
Revises: 44788415924c
Create Date: 2025-05-26 18:22:48.902677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2c0e0e5d20'
down_revision: Union[str, None] = '44788415924c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

subcategory_enum = sa.Enum(
    "BOARD", "PUZZLE", "CONUNDRUM",
    name="subcategory"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    subcategory_enum.create(op.get_bind())

    op.add_column("board_games", sa.Column(
        "subcategory",
        subcategory_enum,
        nullable=False,
        server_default="BOARD"
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("board_games", "subcategory")
    subcategory_enum.drop(op.get_bind())


    # ### end Alembic commands ###