"""Added payment_methods table

Revision ID: b9ff958da8f3
Revises: 5a963e6ccbea
Create Date: 2025-11-13 14:48:20.758843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ff958da8f3'
down_revision: Union[str, None] = '5a963e6ccbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('cart_or_scholar_pack', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('winter_e_support', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('e_book', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('upon_receipt', sa.Boolean(), nullable=False, server_deafult='1'),
    sa.Column('prepay', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_methods')
    # ### end Alembic commands ###