"""changed office_number in meest_post_offices

Revision ID: 0954ee150ac4
Revises: 0177a840894c
Create Date: 2025-11-26 00:37:38.761949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0954ee150ac4'
down_revision: Union[str, None] = '0177a840894c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meest_post_offices', schema=None) as batch_op:
        batch_op.drop_constraint('meest_post_offices_office_number_key', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meest_post_offices', schema=None) as batch_op:
        batch_op.create_unique_constraint('meest_post_offices_office_number_key', ['office_number'])


    # ### end Alembic commands ###