"""Added is_notebook field to books table

Revision ID: 4d506006e870
Revises: ee74d732f47a
Create Date: 2025-08-31 23:22:15.024732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d506006e870'
down_revision: Union[str, None] = 'ee74d732f47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_notebook', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('is_notebook')

    # ### end Alembic commands ###