"""Add packin field

Revision ID: 833936cdd00d
Revises: 2f6abb2f358f
Create Date: 2025-08-26 05:47:12.441953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '833936cdd00d'
down_revision: Union[str, None] = '2f6abb2f358f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE accessories_events_enum AS ENUM ('На всі випадки життя')")
    op.execute("CREATE TYPE accessory_theme_enum AS ENUM ('Класична', 'Відомі люди і песронажі', 'Література')")
    op.execute(
        "CREATE TYPE accessory_seria_enum AS ENUM ('Кіт та собака', 'Діячі', 'Двір шипів та троянд', 'Кажан і кошеня', 'Ніч у Києві', 'Одного разу розбите серце', 'Трон зі скла')")

    with op.batch_alter_table('book_accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packing', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('event', sa.Enum('На всі випадки життя', name='accessories_events_enum'), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.Enum('Класична', 'Відомі люди і песронажі', 'Література', name='accessory_theme_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_accessories', schema=None) as batch_op:
        batch_op.drop_column('event')
        batch_op.drop_column('packing')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###