"""Added hobby_subcategories table

Revision ID: c5a9f6fc3917
Revises: 34064accb2ec
Create Date: 2025-08-15 06:03:32.714610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a9f6fc3917'
down_revision: Union[str, None] = '34064accb2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobby_subcategories',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=55), nullable=False),
    sa.Column('images_src', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['hobby_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hobby_subcategories')
    # ### end Alembic commands ###