"""Add promotion table

Revision ID: e86d6fd93387
Revises: d44cc43dd1c4
Create Date: 2025-04-11 12:55:24.132939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86d6fd93387'
down_revision: Union[str, None] = 'd44cc43dd1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('image', sa.String(length=200), server_default='', nullable=False),
    sa.Column('short_description', sa.Text(), server_default='', nullable=False),
    sa.Column('long_description', sa.Text(), server_default='', nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions')
    # ### end Alembic commands ###