"""Added edition and book_format fields to book_info table

Revision ID: 19d9d647a4aa
Revises: 9298583b8573
Create Date: 2025-10-02 02:06:16.270357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d9d647a4aa'
down_revision: Union[str, None] = '9298583b8573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edition', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('book_format', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('book_format')
        batch_op.drop_column('edition')

    # ### end Alembic commands ###