"""add link field to sidebars table

Revision ID: c351ac8ad0dc
Revises: 7da0da22dc42
Create Date: 2025-07-03 00:53:52.406597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c351ac8ad0dc'
down_revision: Union[str, None] = '7da0da22dc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishings', schema=None) as batch_op:
        batch_op.drop_index('publishing_title_trgm_idx', postgresql_using='gin')

    with op.batch_alter_table('sidebars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=255), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sidebars', schema=None) as batch_op:
        batch_op.drop_column('link')

    with op.batch_alter_table('publishings', schema=None) as batch_op:
        batch_op.create_index('publishing_title_trgm_idx', ['title'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###