"""Added illustrator_book_association  table and related it with books table

Revision ID: 65fb5f5a8b37
Revises: 4c75bcfcf6ff
Create Date: 2025-10-20 01:33:46.960555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fb5f5a8b37'
down_revision: Union[str, None] = '4c75bcfcf6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illustrator_book_association',
    sa.Column('illustrator_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['illustrator_id'], ['book_illustrators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'illustrator_id', name='idx_unique_illustrator_book')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('illustrator_book_association')
    # ### end Alembic commands ###