"""Added orders table

Revision ID: 7c401ea180af
Revises: 6db1efc0018e
Create Date: 2025-12-10 08:27:58.784044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c401ea180af'
down_revision: Union[str, None] = '6db1efc0018e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('for_charity', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('other_person_get', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('delivery_method', sa.Enum('ukrpostOffice', 'ukrpostCourier', 'newPostCourier', 'meestPost', 'newPostToOffice', 'newPostToMailBox', 'YakabooShop', name='delivery_method'), server_default='ukrpostOffice', nullable=False),
    sa.Column('getter_first_name', sa.String(length=255), nullable=True),
    sa.Column('getter_last_name', sa.String(length=255), nullable=True),
    sa.Column('getter_phone_number', sa.String(length=10), nullable=True),
    sa.Column('need_call', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('participant', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('have_questions', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('new_post_courier_delivery_address', sa.String(length=255), nullable=True),
    sa.Column('new_post_courier_delivery_apartment_number', sa.Integer(), nullable=True),
    sa.Column('new_post_courier_house_number', sa.Integer(), nullable=True),
    sa.Column('new_post_delivery_address', sa.String(length=255), nullable=True),
    sa.Column('ukrpost_courier_address', sa.String(length=255), nullable=True),
    sa.Column('ukrpost_courier_apartment_number', sa.Integer(), nullable=True),
    sa.Column('ukrpost_courier_house_number', sa.Integer(), nullable=True),
    sa.Column('ukrpost_user_first_name_for_courier', sa.String(length=255), nullable=True),
    sa.Column('ukrpost_courier_user_middle_name_for_courier', sa.String(length=255), nullable=True),
    sa.Column('ukrpost_user_name_for_courier', sa.String(length=255), nullable=True),
    sa.Column('ukrpost_office_user_name', sa.String(length=255), nullable=True),
    sa.Column('ukrpost_office_user_middle_name', sa.String(length=255), nullable=True),
    sa.Column('ukrpost_office_user_last_name', sa.String(length=255), nullable=True),
    sa.Column('ukrpost_post_index', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Enum('scholarPack', 'eSupport', 'eBook', 'cashOrCart', 'prepay', 'privatePay', 'monoPay', name='payment_method_type'), server_default='scholarPack', nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ORDERED', 'DELIVERED', 'FINISHED', name='order_status_type'), server_default='ORDERED', nullable=False),
    sa.Column('total_sum', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('new_post_office_number', sa.Integer(), nullable=True),
    sa.Column('new_post_postomat_id', sa.Integer(), nullable=True),
    sa.Column('ukrpost_office_id', sa.Integer(), nullable=True),
    sa.Column('meest_office_id', sa.Integer(), nullable=True),
    sa.Column('promo_usage_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['meest_office_id'], ['meest_post_offices.id'], ),
    sa.ForeignKeyConstraint(['new_post_office_number'], ['new_post_offices.id'], ),
    sa.ForeignKeyConstraint(['new_post_postomat_id'], ['new_post_postomats.id'], ),
    sa.ForeignKeyConstraint(['promo_usage_id'], ['promo_code_usages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ukrpost_office_id'], ['ukrpost_offices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('orders')
    # ### end Alembic commands ###