"""Change hobby_category images_src field structure

Revision ID: 00147d82dd2e
Revises: d48d85f19403
Create Date: 2025-08-04 06:55:46.234026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00147d82dd2e'
down_revision: Union[str, None] = 'd48d85f19403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_src', sa.JSON(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('images_src')

    # ### end Alembic commands ###