"""Add main_description to promotions table

Revision ID: 2628aeee9be2
Revises: 1ff0416d4cba
Create Date: 2025-04-30 13:42:13.313348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2628aeee9be2'
down_revision: Union[str, None] = '1ff0416d4cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_description', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_column('main_description')

    # ### end Alembic commands ###