"""Added subcategory_images table

Revision ID: f159b8a636a7
Revises: 65fb5f5a8b37
Create Date: 2025-10-21 12:59:13.559658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f159b8a636a7'
down_revision: Union[str, None] = '65fb5f5a8b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory_images',
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['sub_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategory_images')
    # ### end Alembic commands ###