"""Added book_series table

Revision ID: fcb11c783ebe
Revises: 19d9d647a4aa
Create Date: 2025-10-02 02:20:37.673424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb11c783ebe'
down_revision: Union[str, None] = '19d9d647a4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_series',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_book_seria', 'book_series', ['seria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_seria', type_='foreignkey')
        batch_op.drop_column('seria_id')

    op.drop_table('book_series')
    # ### end Alembic commands ###