"""Chaned board_game_age_id field in hobby_ages_association

Revision ID: d1820e21aeaa
Revises: 00147d82dd2e
Create Date: 2025-08-06 05:41:48.096763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1820e21aeaa'
down_revision: Union[str, None] = '00147d82dd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby_ages_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_game_age_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('hobby_ages_association_board_game_age_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'board_game_ages', ['board_game_age_id'], ['id'])
        batch_op.drop_column('board_game_age')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby_ages_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_game_age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hobby_ages_association_board_game_age_fkey', 'board_game_ages', ['board_game_age'], ['id'])
        batch_op.drop_column('board_game_age_id')

    # ### end Alembic commands ###