"""Added is_active field in book_series table

Revision ID: fcf258a7f5ed
Revises: fcb11c783ebe
Create Date: 2025-10-02 02:23:48.522856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf258a7f5ed'
down_revision: Union[str, None] = 'fcb11c783ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_series', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###