"""add author_facts table

Revision ID: 997b37df93f4
Revises: c351ac8ad0dc
Create Date: 2025-07-08 03:24:32.975949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997b37df93f4'
down_revision: Union[str, None] = 'c351ac8ad0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_facts',
    sa.Column('fact_text', sa.Text(), server_default='', nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id')
    )
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.execute("DROP INDEX IF EXISTS idx_author_first_name_trgm")
        batch_op.execute("DROP INDEX IF EXISTS idx_author_last_name_trgm")

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_top', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_promo', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_in_chart', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('stars', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('promo_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('promo_price')
        batch_op.drop_column('stars')
        batch_op.drop_column('is_in_chart')
        batch_op.drop_column('is_promo')
        batch_op.drop_column('is_top')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index('idx_author_last_name_trgm', ['last_name'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_author_first_name_trgm', ['first_name'], unique=False, postgresql_using='gin')

    op.drop_table('author_facts')
    # ### end Alembic commands ###