"""Add book_accessories, accessories_images, accessories_brands and accessories category tables

Revision ID: 82b19c46e2bd
Revises: 4b919d1092d4
Create Date: 2025-08-25 12:42:47.719274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b19c46e2bd'
down_revision: Union[str, None] = '4b919d1092d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessories_brands',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), server_default='', nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accessories_categories',
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('slug', sa.String(length=70), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('book_accessories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), server_default='', nullable=False),
    sa.Column('article', sa.String(length=25), nullable=False),
    sa.Column('size', sa.String(length=15), server_default='', nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('is_in_top', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_new', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_in_stock', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('bonuses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('color', sa.JSON(), nullable=True),
    sa.Column('type', sa.Enum('Класична', 'Відомі люди і песронажі', 'Література', name='accessories_types_enum'), nullable=True),
    sa.Column('seria', sa.Enum('Кіт та собака', 'Діячі', 'Двір шипів та троянд', 'Кажан і кошеня', 'Ніч у Києві', 'Одного разу розбите серце', 'Трон зі скла', name='accessories_seria_enum'), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['accessories_brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['accessories_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article'),
    sa.UniqueConstraint('code')
    )
    op.create_table('accessories_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=512), server_default='', nullable=False),
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessory_id'], ['book_accessories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('accessories_images')
    op.drop_table('book_accessories')
    op.drop_table('accessories_categories')
    op.drop_table('accessories_brands')
    # ### end Alembic commands ###