"""Added nullable=True in language field in gift_info table

Revision ID: 7b0e73120bc9
Revises: 8a3ecaf5d389
Create Date: 2025-09-15 08:38:35.486849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b0e73120bc9'
down_revision: Union[str, None] = '8a3ecaf5d389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift_info', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=postgresql.ENUM('UKRAINIAN', 'ENGLISH', 'SPANISH', 'POLISH', 'FRANCE', 'GERMAN', name='gift_languages'),
               nullable=True,
               existing_server_default=sa.text("'UKRAINIAN'::gift_languages"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('gift_info', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=postgresql.ENUM('UKRAINIAN', 'ENGLISH', 'SPANISH', 'POLISH', 'FRANCE', 'GERMAN', name='gift_languages'),
               nullable=False,
               existing_server_default=sa.text("'UKRAINIAN'::gift_languages"))

    # ### end Alembic commands ###