"""Changed indexes in meest_offices table

Revision ID: 6db1efc0018e
Revises: a1c88bc8cf14
Create Date: 2025-12-09 06:46:48.477461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db1efc0018e'
down_revision: Union[str, None] = 'a1c88bc8cf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('new_post_offices', schema=None) as batch_op:
        batch_op.drop_index('idx_new_post_offices_active_id')
        batch_op.drop_index('idx_new_post_offices_active_id_only', postgresql_where='active')
        batch_op.drop_index('idx_new_post_offices_city_active_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_post_offices', schema=None) as batch_op:
        batch_op.create_index('idx_new_post_offices_city_active_id', ['city_id', 'active', 'id'], unique=False)
        batch_op.create_index('idx_new_post_offices_active_id_only', ['id'], unique=False, postgresql_where='active')
        batch_op.create_index('idx_new_post_offices_active_id', ['active', 'id'], unique=False)

    # ### end Alembic commands ###