"""fixed board_games and board_games_info relation

Revision ID: 3924a0986d64
Revises: c49e1d44e7c7
Create Date: 2025-05-21 08:12:07.047006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3924a0986d64'
down_revision: Union[str, None] = 'c49e1d44e7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_game_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_game_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['board_game_id'])
        batch_op.create_foreign_key(None, 'board_games', ['board_game_id'], ['code'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_game_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('board_game_id')

    # ### end Alembic commands ###