"""Added notebook_subcategories table

Revision ID: d520fade46b1
Revises: b8eb2338729f
Create Date: 2025-09-04 01:17:25.651524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd520fade46b1'
down_revision: Union[str, None] = 'b8eb2338729f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook_subcategories',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=55), nullable=False),
    sa.Column('images_src', sa.JSON(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['notebook_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notebook_subcategory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'notebook_subcategories', ['notebook_subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notebook_subcategory_id')

    op.drop_table('notebook_subcategories')
    # ### end Alembic commands ###