"""Added a in_sidebar field in knowledges table

Revision ID: b72b9a7f04b2
Revises: 6a782ce09488
Create Date: 2025-09-22 07:11:24.896353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72b9a7f04b2'
down_revision: Union[str, None] = '6a782ce09488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('knowledges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_sidebar', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledges', schema=None) as batch_op:
        batch_op.drop_column('in_sidebar')

    # ### end Alembic commands ###