"""Added book_edition_groups tablename

Revision ID: 36f9c945b949
Revises: 9f111beea832
Create Date: 2025-10-16 07:30:48.092865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f9c945b949'
down_revision: Union[str, None] = '9f111beea832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edition_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_book_edition_group', 'book_edition_groups', ['edition_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_edition_group', type_='foreignkey')
        batch_op.drop_column('edition_group_id')

    # ### end Alembic commands ###