"""added indexes in meest_post_office table

Revision ID: 1cc39cef18c4
Revises: 0954ee150ac4
Create Date: 2025-11-26 01:36:59.266978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc39cef18c4'
down_revision: Union[str, None] = '0954ee150ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('meest_post_offices', schema=None) as batch_op:
        batch_op.create_index('idx_meest_active', [sa.literal_column('id')], unique=False, postgresql_where=sa.text('active = true'))
        batch_op.create_index('idx_meest_city_active', [sa.literal_column('city_id'), sa.literal_column('id')], unique=False, postgresql_where=sa.text('active = true'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meest_post_offices', schema=None) as batch_op:
        batch_op.drop_index('idx_meest_city_active', postgresql_where=sa.text('active = true'))
        batch_op.drop_index('idx_meest_active', postgresql_where=sa.text('active = true'))

    # ### end Alembic commands ###