"""Added subcategory_banners releted subcategory_banners with categories table and renamed to category_banners

Revision ID: 58843ec02aaa
Revises: 15cf997bca65
Create Date: 2025-10-21 18:04:59.106723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58843ec02aaa'
down_revision: Union[str, None] = '15cf997bca65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_banners',
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('subcategory_banners')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory_banners',
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['sub_categories.id'], name='subcategory_banners_subcategory_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subcategory_banners_pkey')
    )
    op.drop_table('category_banners')
    # ### end Alembic commands ###