"""Added literature_type and literature_program_class fields to books field

Revision ID: 786ea4b96a9b
Revises: 8fe278d02e13
Create Date: 2025-10-27 12:20:18.198419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786ea4b96a9b'
down_revision: Union[str, None] = '8fe278d02e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

literature_type_enum = sa.Enum('FOREIGN', 'UKRAINIAN', name='literature_type')
literature_program_class_enum = sa.Enum(
    'FIFTH', 'SIXTH', 'SEVENTH', 'EIGHTH', 'NINE', 'TENTH', 'ELEVENTH',
    name='literature_program_class'
)



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    literature_type_enum.create(op.get_bind(), checkfirst=True)
    literature_program_class_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('literature_type', literature_type_enum, nullable=True))
        batch_op.add_column(sa.Column('literature_program_class', literature_program_class_enum, nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('literature_program_class')
        batch_op.drop_column('literature_type')

    literature_program_class_enum.drop(op.get_bind(), checkfirst=True)
    literature_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###