"""Add is_subscribed_to_news field to users table

Revision ID: 2597cbb012c1
Revises: c79605b569b2
Create Date: 2025-04-09 12:04:33.662165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2597cbb012c1'
down_revision: Union[str, None] = 'c79605b569b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_subscribed_to_news', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_subscribed_to_news')

    # ### end Alembic commands ###