"""Add new fields to book_info table

Revision ID: 0fa3fbd844c4
Revises: fc499d2d6860
Create Date: 2025-07-21 12:28:19.278933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa3fbd844c4'
down_revision: Union[str, None] = 'fc499d2d6860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('original_name', sa.String(length=255), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('original_name')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###