"""Rename type into theme field in book_accessories

Revision ID: ee74d732f47a
Revises: e641c7361342
Create Date: 2025-08-28 02:12:57.614120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee74d732f47a'
down_revision: Union[str, None] = 'e641c7361342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.Enum('Класична', 'Відомі люди і песронажі', 'Література', name='accessories_types_enum'), nullable=True))
        batch_op.drop_column('type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_accessories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('Класична', 'Відомі люди і песронажі', 'Література', name='accessories_types_enum'), autoincrement=False, nullable=True))
        batch_op.drop_column('theme')

    # ### end Alembic commands ###