"""Added promo_codes and promo_code_usages tables

Revision ID: 2dd53597e4c6
Revises: b9ff958da8f3
Create Date: 2025-11-19 07:23:08.215054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd53597e4c6'
down_revision: Union[str, None] = 'b9ff958da8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('max_uses', sa.Integer(), server_default='100', nullable=False),
    sa.Column('current_uses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENT', 'FIXED', name='discount_type'), server_default='PERCENT', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_code_usages',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), server_default='2025-11-19 07:23:07.382478', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('promo_code_usages')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###