"""Add translators and translator_book_association tables

Revision ID: fd9595e4529f
Revises: 0fa3fbd844c4
Create Date: 2025-07-23 09:14:34.337177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9595e4529f'
down_revision: Union[str, None] = '0fa3fbd844c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_translators',
    sa.Column('first_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('translator_book_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translator_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['translator_id'], ['book_translators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('translator_id', 'book_id', name='idx_unique_translator_book')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translator_book_association')
    op.drop_table('book_translators')
    # ### end Alembic commands ###