"""Added new fields in book_info table

Revision ID: 8031229e8012
Revises: a25a8cee1192
Create Date: 2025-12-24 08:01:46.724228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8031229e8012'
down_revision: Union[str, None] = 'a25a8cee1192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_has_winter_esupport', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('waiting_from', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('is_free_delivery', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('delivery_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uk_delivery_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('uk_delivery_time')
        batch_op.drop_column('delivery_time')
        batch_op.drop_column('is_free_delivery')
        batch_op.drop_column('waiting_from')
        batch_op.drop_column('is_has_winter_esupport')

    # ### end Alembic commands ###