"""Added bonuses field in hobbies table

Revision ID: ffcca87aed4c
Revises: aef2303a6480
Create Date: 2025-08-07 11:08:48.542458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcca87aed4c'
down_revision: Union[str, None] = 'aef2303a6480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonuses', sa.Integer(), server_default='0', nullable=False))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.drop_column('bonuses')

    # ### end Alembic commands ###