"""Create knowledge table

Revision ID: 2767bf3fc4cd
Revises: ec99324640ce
Create Date: 2025-04-04 21:19:05.060420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2767bf3fc4cd'
down_revision: Union[str, None] = 'ec99324640ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledges',
    sa.Column('title', sa.String(length=100), server_default='', nullable=False),
    sa.Column('slug', sa.String(length=100), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledges')
    # ### end Alembic commands ###