"""create board_game_info table

Revision ID: c49e1d44e7c7
Revises: d4f6b8d54cfe
Create Date: 2025-05-20 15:23:35.686146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49e1d44e7c7'
down_revision: Union[str, None] = 'd4f6b8d54cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_game_info',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('article', sa.String(length=30), nullable=False),
    sa.Column('package_size', sa.String(length=30), server_default='', nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('theme', sa.Enum('NATURE', 'VEHICLES', 'ARCHITECTURE', 'COUNTRIES_AND_CITIES', 'ART', 'MOVIES_AND_CARTOONS', 'SHIPS', 'EDUCATIONAL', 'PEOPLE', 'FANTASY', name='theme'), nullable=True),
    sa.Column('language', sa.Enum('UKRAINIAN', 'RUSSIAN', 'ENGLISH', 'FRENCH', 'GERMAN', 'CZECH', 'SLOVAKIAN', 'SPANISH', 'ROMANIAN', 'POLISH', 'HUNGARIAN', name='language'), server_default='UKRAINIAN', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_game_info')
    # ### end Alembic commands ###