"""Added images_src field in sub_categories table and deleted subcategores_images table

Revision ID: 431781e4b4d3
Revises: f159b8a636a7
Create Date: 2025-10-21 14:07:00.106557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431781e4b4d3'
down_revision: Union[str, None] = 'f159b8a636a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subcategory_images')
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images_src', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.drop_column('images_src')

    op.create_table('subcategory_images',
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['sub_categories.id'], name='subcategory_images_subcategory_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subcategory_images_pkey')
    )
    # ### end Alembic commands ###