"""Add footers table

Revision ID: 1ff0416d4cba
Revises: a16880653328
Create Date: 2025-04-24 12:45:56.076465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff0416d4cba'
down_revision: Union[str, None] = 'a16880653328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('footers',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(), server_default='', nullable=False),
    sa.Column('category', sa.Enum('YAKABOO', 'INFO', name='footer_category_enum', create_constraint=True), server_default='YAKABOO', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('footers')
    # ### end Alembic commands ###