"""Changed foreign key restrictions for reviews table

Revision ID: a25a8cee1192
Revises: eff1b4c64a79
Create Date: 2025-12-22 13:19:29.324595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a25a8cee1192'
down_revision: Union[str, None] = 'eff1b4c64a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=80), nullable=True))
        batch_op.drop_constraint('reviews_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_email'], ['email'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###