"""Added privat_bank_parts and monobank_parts field in orders table

Revision ID: 938de517d040
Revises: 7c401ea180af
Create Date: 2025-12-10 08:55:10.367994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938de517d040'
down_revision: Union[str, None] = '7c401ea180af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privat_bank_parts', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('monobank_parts', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_column('monobank_parts')
        batch_op.drop_column('privat_bank_parts')
    # ### end Alembic commands ###