"""create board_games, board_games_brands, board_games_age and game_series tables

Revision ID: d4f6b8d54cfe
Revises: 7f3454ee4b8d
Create Date: 2025-05-20 14:57:57.990873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f6b8d54cfe'
down_revision: Union[str, None] = '7f3454ee4b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_games_brands',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_series',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_games',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('image', sa.Text(), server_default='', nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('filters', sa.Enum('DISCOUNT', 'HIT', name='filter'), nullable=True),
    sa.Column('language', sa.Enum('UKRAINIAN', 'RUSSIAN', 'ENGLISH', 'FRENCH', 'GERMAN', 'CZECH', 'SLOVAKIAN', 'SPANISH', 'ROMANIAN', 'POLISH', 'HUNGARIAN', name='language'), server_default='UKRAINIAN', nullable=False),
    sa.Column('status', sa.Enum('IN_STOCK', 'READY', name='status'), server_default='IN_STOCK', nullable=False),
    sa.Column('type', sa.Enum('FOR_FAMILY', 'DEVELOPMENT', 'CARD', 'FOR_PARTY', 'LOGICAL', 'ECONOMICAL', 'AGILITY', 'WALKING', 'GAMBLING', 'ROMANTIC', 'ROLE', 'FOR_OFFICE', name='type'), nullable=True),
    sa.Column('kind', sa.Enum('GUESS_WHO', 'CLUEDO', 'FUNNY', 'STRATEGIC', 'STUDY', 'INTELLECTUAL', 'ACTIVE', 'MONOPOLY', 'ROAD', 'MILITARY', 'LOTO', 'DJENGA', 'DOMINO', 'SETS', 'TWISTER', 'CHESS', 'EXPLAIN_WORD', 'MAFIA', 'DIXIT', 'ERUDITE', 'BACKGAMMON', 'SOCCER', 'CROCODILE', 'CAPITALIST', 'UNO', 'MAZE', 'SEA_FIGHT', 'FARM', 'SCRABBLE', 'TREASURE_ISLAND', 'CHECKERS', 'FIXIKS', 'TIK_TOE_BOOM', 'HOCKEY', 'BILLIARDS', 'MANCHKIN', 'POKER', 'IMAGINARIUM', 'CASINO', 'EVOLUTION', 'ABALON', name='kind'), nullable=True),
    sa.Column('players_count', sa.Enum('FROM_2_TO_16', 'SOLO', 'FOR_TWO', 'FROM_2_TO_4', 'FROM_2_TO_5', 'FROM_1_TO_8', 'FROM_3_TO_16', 'FROM_3_TO_12', 'FROM_4_TO_16', 'FROM_7', 'FROM_2_TO_6', 'FROM_3_TO_8', name='players_count'), nullable=True),
    sa.Column('theme', sa.Enum('NATURE', 'VEHICLES', 'ARCHITECTURE', 'COUNTRIES_AND_CITIES', 'ART', 'MOVIES_AND_CARTOONS', 'SHIPS', 'EDUCATIONAL', 'PEOPLE', 'FANTASY', name='theme'), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('seria_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['board_games_brands.id'], ),
    sa.ForeignKeyConstraint(['seria_id'], ['game_series.id'], ),
    sa.PrimaryKeyConstraint('code', 'id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('board_game_ages',
    sa.Column('board_game_code', sa.Integer(), nullable=False),
    sa.Column('age', sa.Enum('TEENAGERS', 'FROM_9_TO_12', 'FROM_6_TO_8', 'FROM_3_TO_5', 'PARENTS', 'TO_2_YEARS', name='age_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_game_code'], ['board_games.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_game_ages')
    op.drop_table('board_games')
    op.drop_table('game_series')
    op.drop_table('board_games_brands')
    # ### end Alembic commands ###