"""related board_games and board_game_ages table with m2m relationsip

Revision ID: 178e1785273d
Revises: 4e3d308f665d
Create Date: 2025-05-23 09:11:59.626678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178e1785273d'
down_revision: Union[str, None] = '4e3d308f665d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_game_age_association',
    sa.Column('board_game_id', sa.Integer(), nullable=False),
    sa.Column('age_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['age_id'], ['board_game_ages.id'], ),
    sa.ForeignKeyConstraint(['board_game_id'], ['board_games.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_game_ages', schema=None) as batch_op:
        batch_op.drop_constraint('board_game_ages_board_game_code_fkey', type_='foreignkey')
        batch_op.drop_column('board_game_code')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_game_ages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_game_code', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('board_game_ages_board_game_code_fkey', 'board_games', ['board_game_code'], ['code'])

    op.drop_table('board_game_age_association')
    # ### end Alembic commands ###