"""Added pages_format field in book_info table

Revision ID: 310b6286ed64
Revises: 0b01538fc02b
Create Date: 2025-09-09 03:05:17.821102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310b6286ed64'
down_revision: Union[str, None] = '0b01538fc02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

pages_format_enum = sa.Enum("А1", "A2", "A3", "A4", "A5", name="page_formats")


def upgrade() -> None:
    pages_format_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages_format', pages_format_enum, nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('pages_format')

    pages_format_enum.drop(op.get_bind())

    # ### end Alembic commands ###