"""Add literature_periods

Revision ID: a47d6def31ac
Revises: fd9595e4529f
Create Date: 2025-07-23 11:41:59.454589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47d6def31ac'
down_revision: Union[str, None] = 'fd9595e4529f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('literature_periods',
    sa.Column('title', sa.Enum('ANTIQUE', 'END_19_START_20', 'FROM_17_TO_18', 'WHOLE_20', 'RENAISSANCE', 'MODERN', name='period_title_type_enum'), server_default='MODERN', nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('literature_period_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_book_literature_period', 'literature_periods', ['literature_period_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_literature_period', type_='foreignkey')
        batch_op.drop_column('literature_period_id')

    op.drop_table('literature_periods')
    # ### end Alembic commands ###