"""changed max value for aticle field in hobbies table

Revision ID: 34064accb2ec
Revises: 1f257d901ff0
Create Date: 2025-08-14 10:31:32.808367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34064accb2ec'
down_revision: Union[str, None] = '1f257d901ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.alter_column('article',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.alter_column('article',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###