"""Added link field in subcategory_banners table

Revision ID: d12f5019779c
Revises: 58843ec02aaa
Create Date: 2025-10-21 19:54:17.526344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12f5019779c'
down_revision: Union[str, None] = '58843ec02aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_banners', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###