"""add country_id and city_id fields in delivery_terms table

Revision ID: 7da0da22dc42
Revises: 41407453be1b
Create Date: 2025-06-19 01:30:02.482127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da0da22dc42'
down_revision: Union[str, None] = '41407453be1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_terms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cities', ['city_id'], ['id'])
        batch_op.create_foreign_key(None, 'countries', ['country_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_terms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('city_id')
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###