"""Add authors table

Revision ID: ebfbd7db5c8c
Revises: 2597cbb012c1
Create Date: 2025-04-10 11:12:54.797513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfbd7db5c8c'
down_revision: Union[str, None] = '2597cbb012c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('first_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('slug', sa.String(length=255), server_default='', nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('short_description', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authors')
    # ### end Alembic commands ###