"""Added double_subcategories and double_subcategory_book_association_tables

Revision ID: 2a05be920d1d
Revises: 444108cceec8
Create Date: 2025-10-28 10:11:07.951533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a05be920d1d'
down_revision: Union[str, None] = '444108cceec8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double_subcategories',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('images_src', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subcategory_id'], ['sub_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('double_subcategory_book_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('double_subcategory_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['double_subcategory_id'], ['double_subcategories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'double_subcategory_id', name='idx_unique_double_subcategory_book')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('double_subcategory_book_association')
    op.drop_table('double_subcategories')
    # ### end Alembic commands ###