"""Added created_date to books table

Revision ID: 1054ae458413
Revises: 8031229e8012
Create Date: 2025-12-24 08:06:12.351310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1054ae458413'
down_revision: Union[str, None] = '8031229e8012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), server_default='2025-12-24 08:06:10.178826', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###