"""add contacts table

Revision ID: 0584f285af66
Revises: 30df72b8b7d4
Create Date: 2025-06-04 14:58:52.685752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0584f285af66'
down_revision: Union[str, None] = '30df72b8b7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('social_title', sa.String(length=150), nullable=False),
    sa.Column('link', sa.String(length=255), server_default='', nullable=False),
    sa.Column('icon_title', sa.String(length=100), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###