"""Add hobby_categories table

Revision ID: d48d85f19403
Revises: 7888a46c78b4
Create Date: 2025-08-04 06:18:00.858841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd48d85f19403'
down_revision: Union[str, None] = '7888a46c78b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobby_categories',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=55), nullable=False),
    sa.Column('image', sa.String(length=255), server_default='', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.Enum('Люди', 'Релігія', 'Тварини', 'Квіти', 'Природа, пейзажі', 'Архітектура, Міста і країни', 'Кухня і кулінарія, Натюрморт', name='theme_enum'), server_default='Люди', nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'hobby_categories', ['category_id'], ['id'])
        batch_op.drop_column('language')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobbies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', postgresql.ENUM('UKRAINIAN', 'ENGLISH', name='hobbylanguages'), server_default=sa.text("'UKRAINIAN'::hobbylanguages"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('theme')

    op.drop_table('hobby_categories')
    # ### end Alembic commands ###