"""Added weight_to column to new_post_offices table

Revision ID: 7f55a9a67e34
Revises: 856750344ea7
Create Date: 2025-12-02 10:35:32.291290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f55a9a67e34'
down_revision: Union[str, None] = '856750344ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('new_post_offices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_to', sa.Integer(), nullable=True))

    with op.batch_alter_table('new_post_postomats', schema=None) as batch_op:
        batch_op.drop_index('idx_postomats_city_active_id')
        batch_op.create_index('idx_new_post_postomat_active', ['id'], unique=False, postgresql_where=sa.text('active = true'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_post_postomats', schema=None) as batch_op:
        batch_op.drop_index('idx_new_post_postomat_active', postgresql_where=sa.text('active = true'))
        batch_op.create_index('idx_postomats_city_active_id', ['city_id', 'active', 'id'], unique=False)

    with op.batch_alter_table('new_post_offices', schema=None) as batch_op:
        batch_op.drop_column('weight_to')


    # ### end Alembic commands ###