"""Added present_edition_and_sets field into book_info table

Revision ID: 444108cceec8
Revises: 786ea4b96a9b
Create Date: 2025-10-28 09:15:23.745750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444108cceec8'
down_revision: Union[str, None] = '786ea4b96a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('present_edition_and_sets', sa.String(length=50), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('present_edition_and_sets')

    # ### end Alembic commands ###