"""Added 'print' field in 'book_info' table

Revision ID: a39ad4709448
Revises: 2f771b538909
Create Date: 2026-01-14 15:22:58.075067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39ad4709448'
down_revision: Union[str, None] = '2f771b538909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('print', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('print')

    # ### end Alembic commands ###