"""Added 'publishing_banners' table

Revision ID: 9a9eaa1165f3
Revises: b0af83fdf8a5
Create Date: 2026-04-08 18:51:41.790890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9eaa1165f3'
down_revision: Union[str, None] = 'b0af83fdf8a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishing_banners',
    sa.Column('image_src', sa.Text(), nullable=False),
    sa.Column('publishing_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['publishing_id'], ['publishings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publishing_banners')
    # ### end Alembic commands ###