"""Added link in interesting table

Revision ID: 465347dc80f7
Revises: 1054ae458413
Create Date: 2026-01-05 10:40:37.181584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465347dc80f7'
down_revision: Union[str, None] = '1054ae458413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('interesting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interesting', schema=None) as batch_op:
        batch_op.drop_column('link')


    # ### end Alembic commands ###