"""Added is_new_books_banner field in banners

Revision ID: 31a45d3cfeb0
Revises: 15fed7a27a4d
Create Date: 2026-04-03 17:30:23.059025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a45d3cfeb0'
down_revision: Union[str, None] = '15fed7a27a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new_books_banner', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ##
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_column('created_date')
        batch_op.drop_column('is_new_books_banner')
    # ### end Alembic commands ###