"""Added 'goodreads_rate' field and changed type of 'literature_type' and 'literature_program_class' fields in 'book_info' table

Revision ID: 14cb790842f7
Revises: d9f5441701eb
Create Date: 2026-04-22 18:53:19.579763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14cb790842f7'
down_revision: Union[str, None] = 'd9f5441701eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goodreads_rate', sa.Float(), nullable=True))
        batch_op.alter_column('literature_type',
               existing_type=postgresql.ENUM('FOREIGN', 'UKRAINIAN', name='literature_type'),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('literature_program_class',
               existing_type=postgresql.ENUM('FIFTH', 'SIXTH', 'SEVENTH', 'EIGHTH', 'NINE', 'TENTH', 'ELEVENTH', name='literature_program_class'),
               type_=sa.String(length=90),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.alter_column('literature_program_class',
               existing_type=sa.String(length=90),
               type_=postgresql.ENUM('FIFTH', 'SIXTH', 'SEVENTH', 'EIGHTH', 'NINE', 'TENTH', 'ELEVENTH', name='literature_program_class'),
               existing_nullable=True)
        batch_op.alter_column('literature_type',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('FOREIGN', 'UKRAINIAN', name='literature_type'),
               existing_nullable=True)
        batch_op.drop_column('goodreads_rate')
    # ### end Alembic commands ###