"""Changed 'short_description' and 'long_description' fields in 'publishings' table to just 'description' field

Revision ID: b0af83fdf8a5
Revises: 31a45d3cfeb0
Create Date: 2026-04-07 19:25:34.449046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0af83fdf8a5'
down_revision: Union[str, None] = '31a45d3cfeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('publishings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), server_default='', nullable=False))
        batch_op.drop_column('short_description')
        batch_op.drop_column('long_description')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('long_description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('short_description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###