"""Fixed id in review_reactions table

Revision ID: 1c01f0743b73
Revises: 705b3e087cf4
Create Date: 2026-01-16 02:15:47.131503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c01f0743b73'
down_revision: Union[str, None] = '705b3e087cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_reactions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_review', ['user_id', 'review_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_reactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_review', type_='unique')

    # ### end Alembic commands ###