"""Deleted field 'short_description' in 'authors' table 

Revision ID: 15fed7a27a4d
Revises: 7465136b887f
Create Date: 2026-03-06 11:36:31.803607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15fed7a27a4d'
down_revision: Union[str, None] = '7465136b887f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###