"""Added 'goodreads_rate', 'has_legal_restrictions' and 'status' fields in 'book_info' table

Revision ID: b644af3d20cb
Revises: 14cb790842f7
Create Date: 2026-04-22 19:23:34.883112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b644af3d20cb'
down_revision: Union[str, None] = '14cb790842f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    book_status_enum = postgresql.ENUM(
        'IN_STOCK',
        'PENDING',
        'NOT_IN_STCK',
        'DELIVERY_FROM_UK',
        'DELIVERY_FROM_UKRAINE',
        name='bookstatusenum'
    )
    book_status_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_legal_restrictions', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('status',sa.Enum('IN_STOCK', 'PENDING','NOT_IN_STCK', 'DELIVERY_FROM_UK', 'DELIVERY_FROM_UKRAINE', name='bookstatusenum'
                ),
                server_default='IN_STOCK',
                nullable=True
            )
        )
        batch_op.drop_column('in_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ##
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_column('status')
        batch_op.drop_column('has_legal_restrictions')

    book_status_enum = postgresql.ENUM(name='bookstatusenum')
    book_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###