"""Added 'search_vector' field to 'books', 'authors' and 'publishings' tables

Revision ID: fed210428841
Revises: 4d165d617b5f
Create Date: 2026-01-28 17:03:10.671846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'fed210428841'
down_revision: Union[str, None] = '4d165d617b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
           ALTER TABLE books
           ADD COLUMN IF NOT EXISTS search_vector tsvector
       """)
    op.execute("""
           CREATE INDEX IF NOT EXISTS book_search_idx
           ON books USING gin(search_vector)
       """)

    op.execute("""
           ALTER TABLE authors
           ADD COLUMN IF NOT EXISTS search_vector tsvector
       """)
    op.execute("""
           CREATE INDEX IF NOT EXISTS author_search_idx
           ON authors USING gin(search_vector)
       """)

    op.execute("""
           ALTER TABLE publishings
           ADD COLUMN IF NOT EXISTS search_vector tsvector
       """)
    op.execute("""
           CREATE INDEX IF NOT EXISTS publishing_search_idx
           ON publishings USING gin(search_vector)
       """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
           DROP INDEX IF EXISTS book_search_idx
       """)
    op.execute("""
           ALTER TABLE books
           DROP COLUMN IF EXISTS search_vector
       """)

    op.execute("""
            DROP INDEX IF EXISTS author_search_idx
        """)
    op.execute("""
            ALTER TABLE authors
            DROP COLUMN IF EXISTS search_vector
        """)

    op.execute("""
           DROP INDEX IF EXISTS publishing_search_idx
       """)
    op.execute("""
           ALTER TABLE publishings
           DROP COLUMN IF EXISTS search_vector
       """)

# ### end Alembic commands ###