"""Added 'user_seen_books' table

Revision ID: 5df61857d958
Revises: 5b8c97331769
Create Date: 2026-01-13 01:50:10.843276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df61857d958'
down_revision: Union[str, None] = '5b8c97331769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_seen_books',
    sa.Column('seen_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('idx_books_notebook_false', postgresql_where='(is_notebook = false)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('idx_books_notebook_false', ['id'], unique=False, postgresql_where='(is_notebook = false)')

    op.drop_table('user_seen_books')
    # ### end Alembic commands ###