"""Deleted field 'stars' in 'books' table and 'rate' field in 'book_info' table

Revision ID: 7465136b887f
Revises: baabbb0d8336
Create Date: 2026-03-06 10:35:51.140763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7465136b887f'
down_revision: Union[str, None] = 'baabbb0d8336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('rate')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('stars')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stars', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###