"""Added 'link' field in 'publishing_banners' table

Revision ID: e1c7f30cd0d7
Revises: 9a9eaa1165f3
Create Date: 2026-04-08 20:05:55.264190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c7f30cd0d7'
down_revision: Union[str, None] = '9a9eaa1165f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishing_banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishing_banners', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###