"""Added unique_constraint to 'user_seen_books' table

Revision ID: 2f771b538909
Revises: 778a3c4932b9
Create Date: 2026-01-14 07:21:32.793893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f771b538909'
down_revision: Union[str, None] = '778a3c4932b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user_seen_books', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_book_seen', ['user_id', 'book_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_seen_books', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_book_seen', type_='unique')
    # ### end Alembic commands ###