"""Added 'has_color_cut' field in 'book_info' table

Revision ID: 778a3c4932b9
Revises: 8995b58e0896
Create Date: 2026-01-14 07:01:35.947703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '778a3c4932b9'
down_revision: Union[str, None] = '8995b58e0896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_color_cut', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('has_color_cut')

    # ### end Alembic commands ###