"""Added 'is_for_war' field in 'book_info' table

Revision ID: baabbb0d8336
Revises: fed210428841
Create Date: 2026-02-03 19:06:29.844934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baabbb0d8336'
down_revision: Union[str, None] = 'fed210428841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_for_war', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_info', schema=None) as batch_op:
        batch_op.drop_column('is_for_war')
    # ### end Alembic commands ###